# Generated by Django 5.0.4 on 2024-09-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="is_template",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="template",
        ),
    ]
