# Generated by Django 5.0.4 on 2024-09-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_transaction_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="budget",
        ),
    ]
