# Generated by Django 5.0.4 on 2024-10-16 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_transaction_is_recurring_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringtransaction",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.transaction",
            ),
        ),
    ]
